// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@og/compat/server-fn'
import { getSupabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = (await getSupabase()?.auth.getSession()) ?? { data: { session: null } }
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
