// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { resolveFirst } from '../../../core/resolveEnv';

/**
 * Thrown when Supabase-backed OG functionality is invoked with no Supabase
 * configured. Distinguishable from a genuine query failure so the UI can say
 * "not connected" rather than reporting an error it cannot act on.
 */
export class SupabaseUnconfiguredError extends Error {
  readonly unconfigured = true;
  constructor() {
    super(
      "Supabase is not configured. Set SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY " +
        "to enable OG persistence; LÉLU runs without them.",
    );
    this.name = "SupabaseUnconfiguredError";
  }
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


/**
 * Resolution goes through v1.1's canonical resolver rather than reading
 * import.meta.env directly, so a key supplied under the unprefixed platform
 * name (SUPABASE_URL rather than VITE_SUPABASE_URL) is found — which is how
 * the hosting environment actually delivers it.
 */
function readConfig(): { url: string; key: string } | null {
  const url = resolveFirst("SUPABASE_URL");
  const key = resolveFirst("SUPABASE_PUBLISHABLE_KEY", "SUPABASE_ANON_KEY");
  if (!url || !key) return null;
  return { url, key };
}

/**
 * Is Supabase usable at all?
 *
 * The OG original threw from the client factory when configuration was
 * absent. Under the hybrid that is not allowed: LÉLU must render, chat and
 * think without Supabase (integration brief §5, §20), so callers ask this
 * first and take a degraded path instead of exploding.
 */
export function isSupabaseConfigured(): boolean {
  return readConfig() !== null;
}

function createSupabaseClient() {
  const config = readConfig();
  if (!config) {
    throw new SupabaseUnconfiguredError();
  }
  const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = config;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

/** The client, or null when nothing is configured — never throws. */
export function getSupabase(): ReturnType<typeof createSupabaseClient> | null {
  if (!isSupabaseConfigured()) return null;
  if (!_supabase) _supabase = createSupabaseClient();
  return _supabase;
}

// Import the supabase client like this:
// import { supabase } from "@og/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

