/**
 * ==========================================================
 * LÉLU
 * LOCAL BLENDER ADAPTER
 *
 * Blender is a native application — a browser cannot start it.
 * This adapter has two honest halves:
 *
 *   1. DETECTION — probes a future LÉLU companion bridge on
 *      localhost:8081 (the same host the app's controls live on)
 *      for `blender` capability. In the sandboxed preview there
 *      is no companion, so this reports not-installed truthfully.
 *
 *   2. SCRIPT GENERATION — a REAL, deterministic Blender Python
 *      emitter. It produces the exact .py a companion runtime
 *      would execute headlessly:
 *
 *        blender --background --python scene.py --render-output out.png
 *
 *      Nothing here claims a render happened. The script is the
 *      artifact; the render requires Blender on the runtime host.
 * ==========================================================
 */

import type { LocalBackendKind, LocalBackendStatus } from "./LocalRuntimeTypes";

export interface BlenderMaterial {
  name: string;
  color: [number, number, number];
  metallic?: number;
  roughness?: number;
}

export interface BlenderPrimitive {
  type: "cube" | "uv_sphere" | "cylinder" | "torus";
  name: string;
  location: [number, number, number];
  scale?: [number, number, number];
  material?: string;
}

export interface BlenderSceneSpec {
  name: string;
  primitives: BlenderPrimitive[];
  materials: BlenderMaterial[];
  camera: {
    location: [number, number, number];
    target: [number, number, number];
  };
  resolution?: { x: number; y: number };
  outputPath?: string;
}

const COMPANION_BRIDGE_URL = "http://localhost:8081";
const PROBE_TIMEOUT_MS = 1_000;

export default class LocalBlenderAdapter {
  private static instance: LocalBlenderAdapter | null = null;

  private lastDetection: LocalBackendStatus | null = null;

  public static getInstance(): LocalBlenderAdapter {
    if (!LocalBlenderAdapter.instance) {
      LocalBlenderAdapter.instance = new LocalBlenderAdapter();
    }
    return LocalBlenderAdapter.instance;
  }

  private constructor() {}

  /**
   * Probe the LÉLU companion bridge for a Blender backend.
   * Only a real HTTP response marks Blender as available.
   */
  public async detect(): Promise<LocalBackendStatus> {
    const base = {
      kind: "blender" as LocalBackendKind,
      name: "Blender",
      baseUrl: `${COMPANION_BRIDGE_URL}/blender`,
      models: [],
      checkedAt: Date.now(),
    };
    try {
      const controller = new AbortController();
      const timer = window.setTimeout(() => controller.abort(), PROBE_TIMEOUT_MS);
      let response: Response;
      try {
        response = await fetch(`${COMPANION_BRIDGE_URL}/blender/status`, {
          method: "GET",
          signal: controller.signal,
          headers: { Accept: "application/json" },
        });
      } finally {
        window.clearTimeout(timer);
      }
      if (!response.ok) {
        this.lastDetection = { ...base, reachable: false, error: `HTTP ${response.status}` };
        return this.lastDetection;
      }
      this.lastDetection = { ...base, reachable: true };
      return this.lastDetection;
    } catch (error) {
      const message =
        error instanceof DOMException && error.name === "AbortError"
          ? "No LÉLU companion bridge on localhost:8081 (Blender cannot run inside a browser sandbox)."
          : error instanceof Error
            ? error.message
            : String(error);
      this.lastDetection = { ...base, reachable: false, error: message };
      return this.lastDetection;
    }
  }

  public status(): LocalBackendStatus | null {
    return this.lastDetection;
  }

  /**
   * Emit a real, executable Blender Python script from a scene
   * spec. Deterministic and self-contained: primitives, principled
   * materials, camera aimed at a target, sun light, world color,
   * resolution, save + render.
   */
  public generateScript(spec: BlenderSceneSpec): { fileName: string; script: string } {
    const lines: string[] = [];
    lines.push("# Generated by LÉLU LocalRuntime (deterministic scene emitter)");
    lines.push("import bpy, math");
    lines.push("");
    lines.push(`scene_name = ${JSON.stringify(spec.name)}`);
    lines.push("");
    lines.push("# Fresh scene");
    lines.push("bpy.ops.wm.read_factory_settings(use_empty=True)");
    lines.push("scene = bpy.context.scene");
    lines.push("scene.name = scene_name");
    lines.push("");

    // Materials
    for (const material of spec.materials) {
      lines.push(`mat_${sanitize(material.name)} = bpy.data.materials.new(${JSON.stringify(material.name)})`);
      lines.push(`mat_${sanitize(material.name)}.use_nodes = True`);
      lines.push("bsdf = mat_" + sanitize(material.name) + '.node_tree.nodes["Principled BSDF"]');
      const color = material.color.map((c) => c.toFixed(4)).join(", ");
      lines.push(`bsdf.inputs["Base Color"].default_value = (${color}, 1.0)`);
      lines.push(`bsdf.inputs["Metallic"].default_value = ${(material.metallic ?? 0).toFixed(4)}`);
      lines.push(`bsdf.inputs["Roughness"].default_value = ${(material.roughness ?? 0.6).toFixed(4)}`);
      lines.push("");
    }

    // Primitives
    for (const primitive of spec.primitives) {
      lines.push(`bpy.ops.mesh.primitive_${primitive.type}_add(location=(${primitive.location.map((n) => n.toFixed(4)).join(", ")}))`);
      lines.push(`prim = bpy.context.object`);
      lines.push(`prim.name = ${JSON.stringify(primitive.name)}`);
      if (primitive.scale) {
        lines.push(`prim.scale = (${primitive.scale.map((n) => n.toFixed(4)).join(", ")})`);
      }
      if (primitive.material) {
        const matRef = `mat_${sanitize(primitive.material)}`;
        lines.push(`if "${matRef}" in globals():`);
        lines.push(`    prim.data.materials.append(${matRef})`);
      }
      lines.push("");
    }

    // Camera
    const [cx, cy, cz] = spec.camera.location;
    const [tx, ty, tz] = spec.camera.target;
    lines.push("# Camera aimed at the target");
    lines.push('cam_data = bpy.data.cameras.new("Camera")');
    lines.push('cam = bpy.data.objects.new("Camera", cam_data)');
    lines.push("scene.collection.objects.link(cam)");
    lines.push(`cam.location = (${cx.toFixed(4)}, ${cy.toFixed(4)}, ${cz.toFixed(4)})`);
    lines.push(`direction = (${(tx - cx).toFixed(4)}, ${(ty - cy).toFixed(4)}, ${(tz - cz).toFixed(4)})`);
    lines.push("cam.rotation_euler = (");
    lines.push("    math.asin(direction[2] / (math.sqrt(direction[0]**2 + direction[1]**2 + direction[2]**2) or 1)),");
    lines.push("    0,");
    lines.push("    math.atan2(direction[0], direction[1]),");
    lines.push(")");
    lines.push("scene.camera = cam");
    lines.push("");

    // Sun light
    lines.push("# Sun light");
    lines.push('sun_data = bpy.data.lights.new("Sun", "SUN")');
    lines.push("sun_data.energy = 4.0");
    lines.push('sun = bpy.data.objects.new("Sun", sun_data)');
    lines.push("scene.collection.objects.link(sun)");
    lines.push("sun.rotation_euler = (0.8, 0.0, 0.6)");
    lines.push("");

    // World
    lines.push("# World background");
    lines.push('world = bpy.data.worlds.new("World")');
    lines.push('world.use_nodes = True');
    lines.push('world.node_tree.nodes["Background"].inputs[0].default_value = (0.01, 0.01, 0.03, 1.0)');
    lines.push("scene.world = world");
    lines.push("");

    // Resolution + output + render
    const resolution = spec.resolution ?? { x: 1920, y: 1080 };
    lines.push(`scene.render.resolution_x = ${resolution.x}`);
    lines.push(`scene.render.resolution_y = ${resolution.y}`);
    lines.push('scene.render.image_settings.file_format = "PNG"');
    lines.push(`scene.render.filepath = ${JSON.stringify(spec.outputPath ?? `//render_${spec.name.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}.png`)}`);
    lines.push("");
    lines.push("bpy.ops.wm.save_as_mainfile(filepath=scene.render.filepath.replace('.png', '.blend'))");
    lines.push('print("LÉLU_BLENDER_RENDER:", scene.render.filepath)');
    lines.push('bpy.ops.render.render(write_still=True)');

    return {
      fileName: `${spec.name.replace(/[^a-z0-9]+/gi, "_").toLowerCase()}_scene.py`,
      script: lines.join("\n") + "\n",
    };
  }

  /** Default scene used by the runtime self-test — a real cube scene. */
  public defaultCubeScene(): BlenderSceneSpec {
    return {
      name: "LeleuTestCube",
      primitives: [
        { type: "cube", name: "Cube", location: [0, 0, 0], scale: [1, 1, 1], material: "CyanGlass" },
        { type: "torus", name: "Ring", location: [2.2, 0, 0.6], scale: [0.6, 0.6, 0.6], material: "Magenta" },
      ],
      materials: [
        { name: "CyanGlass", color: [0.05, 0.95, 1.0], metallic: 0.1, roughness: 0.15 },
        { name: "Magenta", color: [1.0, 0.1, 0.7], metallic: 0.6, roughness: 0.3 },
      ],
      camera: { location: [6, -6, 4], target: [0, 0, 0.5] },
      resolution: { x: 1280, y: 720 },
      outputPath: "//render_test_cube.png",
    };
  }
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^_+|_+$/g, "") || "obj";
}